# Generated by Django 5.0.4 on 2024-04-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
